<?php

namespace App\Http\Controllers;

// use App\Models\Checker;
use App\Models\Employee;
use App\Models\Permission;
use Illuminate\Http\Request;

class UserPagePermissionController extends Controller
{
    /**
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function editPermission(Request $request) {
		$user_id = $request->id;
		$row = Permission::where('user_id', '=', $user_id)->first();
        $emp = Employee::where('user_id', '=', $user_id)->first();
        $response['row'] = $row;
        $response['emp'] = $emp;
        // $checker = Checker::where('user_id', '=', $user_id)->first();
        // $response['checker'] = $checker;
		return response()->json($response, 200);
	}

    /**
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function updatePermission(Request $request) {
        $this->validate($request, [
            'user_id' => 'required|integer'
        ]);
        $permission = Permission::where('user_id', $request->user_id)->first();
        if(!$permission){
            return response()->json(['success' => false, 'message' => 'Permission not found against user ID'], 404);
        }
        $updateArray = $request->only([
            'customer_list',
            'customer_create',
            'customer_edit',
            'customer_delete',
            'contact_person_list',
            'contact_person_create',
            'contact_person_edit',
            'contact_person_delete',
            'consignee_list',
            'consignee_create',
            'consignee_edit',
            'consignee_delete',
            'customer_attachment_list',
            'customer_attachment_create',
            'customer_attachment_edit',
            'customer_attachment_delete',
            'directory_list',
            'directory_create',
            'directory_edit',
            'employee_list',
            'employee_create',
            'employee_edit',
            'irm_list',
            'irm_create',
            'irm_edit',
            'irm_delete',
            'invoice_list',
            'invoice_create',
            'invoice_edit',
            'invoice_delete',
            'product_list',
            'product_create',
            'product_edit',
            'product_vendor_list',
            'product_vendor_create',
            'product_vendor_edit',
            'product_vendor_delete',
            'product_attachment_list',
            'product_attachment_create',
            'product_attachment_edit',
            'product_attachment_delete',
            'purchase_order_list',
            'purchase_order_create',
            'purchase_order_edit',
            'procurement_list',
            'procurement_create',
            'procurement_edit',
            'procurement_vendor_list',
            'procurement_vendor_create',
            'procurement_vendor_edit',
            'procurement_vendor_delete',
            'procurement_attachment_list',
            'procurement_attachment_create',
            'procurement_attachment_edit',
            'procurement_attachment_delete',
            'quotation_list',
            'quotation_create',
            'quotation_edit',
            'quotation_delete',
            'recruitment_list',
            'recruitment_create',
            'recruitment_edit',
            'recruitment_delete',
            'recruitment_attachment_list',
            'recruitment_attachment_create',
            'recruitment_attachment_edit',
            'recruitment_attachment_delete',
            'recruitment_candidate_list',
            'recruitment_candidate_create',
            'recruitment_candidate_edit',
            'recruitment_candidate_delete',
            'vendor_list',
            'vendor_create',
            'vendor_edit',
            'vendor_contact_list',
            'vendor_contact_create',
            'vendor_contact_edit',
            'vendor_contact_delete',
            'vendor_attachment_list',
            'vendor_attachment_create',
            'vendor_attachment_edit',
            'vendor_attachment_delete',
            'vendor_purchase_list',
            'vendor_purchase_create',
            'vendor_purchase_edit',
            'vendor_purchase_delete',
            'lead_list',
            'lead_create',
            'lead_edit',
            'lead_delete',
            'customer_view_list',
            'customer_view_create',
            'customer_view_edit',
            'customer_view_delete',
            'assign_lead_list',
            'assign_lead_create',   
            'assign_lead_edit',
            'assign_lead_delete',
            'assignee_lead_list',
            'assignee_lead_create',
            'assignee_lead_edit',
            'assignee_lead_delete',
            'lead_source_list',
            'lead_source_create',
            'lead_source_edit',
            'lead_source_delete',
            'warehouse_list',
            'warehouse_create',
            'warehouse_edit',
            'warehouse_delete',
            'attachment_list',
            'attachment_create',
            'attachment_edit',
            'attachment_delete',
            'assets_list',
            'assets_create',
            'assets_edit',
            'assets_delete',
            'asset_type_list',
            'asset_type_create',
            'asset_type_edit',
            'asset_type_delete',
            'bank_account_list',
            'bank_account_create',
            'bank_account_edit',
            'bank_account_delete',
            'bank_details_list',
            'bank_details_create',
            'bank_details_edit',
            'bank_details_delete',
            'business_task_list',
            'business_task_create',
            'business_task_edit',
            'business_task_delete',
            'business_task_team_list',
            'business_task_team_create',
            'business_task_team_edit',
            'business_task_team_delete',
            'business_task_view_list',
            'business_task_view_create',
            'business_task_view_edit',
            'business_task_view_delete',
            'business_task_edit_list',
            'business_task_edit_create',
            'business_task_edit_edit',
            'business_task_edit_delete',
            'company_details_edit',
            'category_list',
            'category_create',
            'category_edit',
            'category_delete',
            'compliance_list',
            'compliance_create',
            'compliance_edit',
            'compliance_delete',
            'credentials_create',
            'credentials_list',
            'credentials_edit',
            'credentials_delete',
            'currency_list',
            'currency_create',
            'currency_edit',
            'currency_delete',
            'customer_base_list',
            'customer_base_create',
            'customer_base_edit',
            'customer_base_delete',
            'customer_type_list',
            'customer_type_create',
            'customer_type_edit',
            'customer_type_delete',
            'department_list',
            'department_create',
            'department_edit',
            'department_delete',
            'designation_list',
            'designation_create',
            'designation_edit',
            'designation_delete',
            'ebrc_list',
            'ebrc_create',
            'ebrc_edit',
            'ebrc_delete',
            'entity_type_list',
            'entity_type_create',
            'entity_type_edit',
            'entity_type_delete',
            'examine_list',
            'examine_create',
            'examine_edit',
            'examine_delete',
            'ffd_list',
            'ffd_create',
            'ffd_edit',
            'ffd_delete',
            'ffd_contact_list',
            'ffd_contact_create',
            'ffd_contact_edit',
            'ffd_contact_delete',
            'gst_percent_list',
            'gst_percent_create',
            'gst_percent_edit',
            'gst_percent_delete',
            'hsn_code_list',
            'hsn_code_create',
            'hsn_code_edit',
            'hsn_code_delete',
            'inco_terms_list',
            'inco_terms_create',
            'inco_terms_edit',
            'inco_terms_delete',
            'kpi_list',
            'kpi_create',
            'kpi_edit',
            'kpi_delete',
            'location_detail_list',
            'location_detail_create',
            'location_detail_edit',
            'location_detail_delete',
            'product_condition_list',
            'product_condition_create',
            'product_condition_edit',
            'product_condition_delete',
            'product_type_list',
            'product_type_create',
            'product_type_edit',
            'product_type_delete',
            'regulatory_list',
            'regulatory_create',
            'regulatory_edit',
            'regulatory_delete',
            'role_list',
            'role_create',
            'role_edit',
            'role_delete',
            'segment_list',
            'segment_create',
            'segment_edit',
            'segment_delete',
            'stages_list',
            'stages_create',
            'stages_edit',
            'stages_delete',
            'terms_and_conditions_list',
            'terms_and_conditions_create',
            'terms_and_conditions_edit',
            'terms_and_conditions_delete',
            'unit_of_measurement_list',
            'unit_of_measurement_create',
            'unit_of_measurement_edit',
            'unit_of_measurement_delete',
            'vendor_type_list',
            'vendor_type_create',
            'vendor_type_edit',
            'vendor_type_delete',
            'vendor_behavior_list',
            'vendor_behavior_create',
            'vendor_behavior_edit',
            'vendor_behavior_delete',
            'prev_stage_list',
            'prev_stage_create',
            'prev_stage_edit',
            'prev_stage_delete',
        ]);

		Permission::where("user_id", $request->user_id)->update($updateArray);

		return response()->json(['success' => true, 'message' => 'Permissions updated successfully'],200);
	}
}
